"use client";
import Link from "next/link";
import {useEffect,useRef,useState} from "react";
import {Button,Chip,Paper} from "@mui/material";
import ArrowBackRounded from "@mui/icons-material/ArrowBackRounded";
import ArrowForwardRounded from "@mui/icons-material/ArrowForwardRounded";
import CheckCircleRounded from "@mui/icons-material/CheckCircleRounded";
import PauseRounded from "@mui/icons-material/PauseRounded";
import PlayArrowRounded from "@mui/icons-material/PlayArrowRounded";
import AcademyHeader from "@/app/_components/AcademyHeader";
import {ayetAudioPath,sureSourceUrl,type NamazAyeti,type NamazSuresi} from "@/src/data/namaz-sureleri";
import {logActivity,scheduleReview} from "@/src/lib/progress";

const colors=["#f6cf88","#b9e3d4","#ffc2a5","#c8d9ff","#f4b9cf"];
export default function AyetDetayClient({sure,ayah}:{sure:NamazSuresi;ayah:NamazAyeti}){
 const audio=useRef<HTMLAudioElement>(null);const [playing,setPlaying]=useState(false);const [done,setDone]=useState(false);const previous=sure.ayahs[ayah.number-2];const next=sure.ayahs[ayah.number];const key=`${sure.slug}-${ayah.number}`;
 useEffect(()=>{try{setDone(JSON.parse(localStorage.getItem("namaz-sureleri-progress")||"[]").includes(key))}catch{}},[key]);
 function toggle(){const player=audio.current;if(!player)return;if(playing){player.pause();setPlaying(false)}else{player.play().then(()=>setPlaying(true)).catch(()=>setPlaying(false))}player.onended=()=>setPlaying(false)}
 function finish(){let values:string[]=[];try{values=JSON.parse(localStorage.getItem("namaz-sureleri-progress")||"[]")}catch{}if(!values.includes(key))values.push(key);localStorage.setItem("namaz-sureleri-progress",JSON.stringify(values));setDone(true);logActivity();scheduleReview(key,"namaz",`${sure.name}, ${ayah.number}. ayet`,`/namaz-sureleri/${sure.slug}/${ayah.number}`)}
 const theory=[ayah.explanation,...sure.context,`Bu ayeti çalışırken önce kârîyi dikkatle dinle, ardından kelime gruplarını durak yerlerine dikkat ederek üç kez tekrar et. Kısa anlamı kendi cümlenle anlatman, Arapça metin ile mesaj arasındaki bağı güçlendirir. Açıklamalar eğitim amacıyla hazırlanmış özgün özetlerdir; farklı yorumları karşılaştırmak için aşağıdaki kaynakçaya başvurabilirsin.`];
 return <main className="min-h-screen bg-[#f7f3ec] text-[#183f3a]"><audio ref={audio} src={ayetAudioPath(sure,ayah.number)} preload="auto"/><AcademyHeader title="Namaz Sureleri"/>
  <section className="mx-auto max-w-6xl space-y-6 px-5 py-8 sm:px-8"><Link href={`/namaz-sureleri/${sure.slug}`} className="inline-flex items-center gap-2 font-extrabold text-[#244a70]"><ArrowBackRounded/> {sure.name} ayetleri</Link>
   <Paper elevation={0} className="!rounded-[2rem] !bg-[#244a70] !p-7 !text-white sm:!p-10"><div className="flex flex-wrap items-center justify-between gap-3"><Chip label={`${sure.name.toUpperCase()} · ${ayah.number}. AYET`} className="!bg-[#f6cf88] !font-black !tracking-wider !text-blue-950"/><span className="text-sm font-bold text-blue-100">{sure.period}</span></div><h1 className="mt-5 font-serif text-4xl font-bold sm:text-6xl">{sure.name} · {ayah.number}. Ayet</h1><div className="mt-8 rounded-3xl bg-white/10 p-6 text-center ring-1 ring-white/15"><p dir="rtl" className="font-serif text-4xl leading-[2.1] sm:text-6xl">{ayah.arabic.split(" ").map((word,index)=><span key={index} style={{color:colors[index%colors.length]}} className="mx-2">{word}</span>)}</p><p className="mt-5 text-lg leading-8 text-blue-50">{ayah.shortMeaning}</p><Button onClick={toggle} startIcon={playing?<PauseRounded/>:<PlayArrowRounded/>} variant="contained" sx={{mt:3,borderRadius:3,bgcolor:"#f6cf88",color:"#183f3a",px:3,py:1.3,fontWeight:900,"&:hover":{bgcolor:"#ffe1a7"}}}>{playing?"Duraklat":"Kârîden dinle"}</Button></div></Paper>
   <Paper component="article" elevation={0} className="!rounded-3xl !p-7 ring-1 ring-blue-950/10 sm:!p-9"><p className="text-xs font-black tracking-[.18em] text-[#b65f38]">AYRINTILI AÇIKLAMA</p><h2 className="mt-2 font-serif text-4xl font-bold">Ayetin anlam katmanları</h2><p className="mt-3 text-sm leading-6 text-blue-950/55">Metin doğrudan uzun alıntı içermez; güvenilir yayınlar karşılaştırılarak çocukların anlayabileceği bir dille özgün biçimde özetlenmiştir.</p><div className="mt-8 space-y-7">{theory.map((paragraph,index)=><div key={index} className="grid gap-4 sm:grid-cols-[48px_1fr]"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-blue-50 font-black text-[#244a70]">{index+1}</span><p className="text-[17px] leading-8 text-blue-950/80">{paragraph}</p></div>)}</div></Paper>
   <div className="grid gap-5 lg:grid-cols-[1fr_330px]"><Paper elevation={0} className="!rounded-3xl !bg-[#fff7e8] !p-7 ring-1 ring-amber-200"><p className="text-xs font-black tracking-[.18em] text-amber-800">BOL PRATİK</p><h2 className="mt-2 font-serif text-3xl font-bold">Dinle, tekrar et, anlat</h2><div className="mt-5 grid gap-3">{["Ayeti bir kez yalnızca dinle; uzatma ve durakları fark et.","Sesi yeniden başlatıp her kelime grubunun ardından tekrar et.","Kısa anlamı ekrana bakmadan kendi cümlenle anlat.","Ayeti üç kez baştan sona oku ve tamamlandı olarak işaretle."].map((item,index)=><button key={item} onClick={toggle} className="flex items-center gap-4 rounded-2xl bg-white p-4 text-left shadow-sm ring-1 ring-amber-200 transition hover:-translate-y-0.5"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-[#b65f38] text-sm font-black text-white">{index+1}</span><span className="text-sm font-semibold leading-6">{item}</span></button>)}</div></Paper><Paper elevation={0} className="!rounded-3xl !p-6 ring-1 ring-blue-950/10"><p className="text-[11px] font-black uppercase tracking-wider text-blue-950/50">Kaynakça</p><p className="mt-2 text-xs leading-5 text-blue-950/55">Açıklamalar özgün özetlerdir. Ayrıntılı okuma için:</p><div className="mt-4 space-y-4"><a href={sureSourceUrl(sure)} target="_blank" rel="noreferrer" className="block text-xs font-bold leading-5 text-[#244a70] underline decoration-blue-200 underline-offset-4">Diyanet İşleri Başkanlığı<br/><span className="font-medium">Kur’an Yolu · {sure.name} tefsiri</span></a><a href="https://kuran.diyanet.gov.tr/" target="_blank" rel="noreferrer" className="block text-xs font-bold leading-5 text-[#244a70] underline decoration-blue-200 underline-offset-4">Diyanet Kur’an Portalı<br/><span className="font-medium">Kur’an-ı Kerim meali ve tefsiri</span></a></div></Paper></div>
   <div className="flex flex-wrap items-center justify-between gap-3 rounded-3xl bg-white p-5 ring-1 ring-blue-950/10"><div>{previous&&<Button component={Link} href={`/namaz-sureleri/${sure.slug}/${previous.number}`} startIcon={<ArrowBackRounded/>} sx={{color:"#244a70",fontWeight:800}}>Önceki ayet</Button>}</div><Button onClick={finish} variant="contained" startIcon={<CheckCircleRounded/>} sx={{borderRadius:3,bgcolor:done?"#287969":"#244a70",fontWeight:900,px:3,py:1.3}}>{done?"Tamamlandı":"Ayeti tamamla"}</Button><div>{next&&<Button component={Link} href={`/namaz-sureleri/${sure.slug}/${next.number}`} endIcon={<ArrowForwardRounded/>} sx={{color:"#b65f38",fontWeight:800}}>Sonraki ayet</Button>}</div></div>
  </section>
 </main>
}
